#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# devbox-worker — one Foreman task, start to PR, in a throwaway container.
#
# Foreman (platform/foreman) launches this image once per task with only
#   FOREMAN_URL  TASK_TOKEN
# in the environment; the model key and the GitHub token come from the job's
# mounted secrets (MODEL_API_KEY, GH_TOKEN). Everything else is fetched:
#   GET  $FOREMAN_URL/api/worker/task     → repo, branch, prompt, model, limits
#   POST $FOREMAN_URL/api/worker/events   ← started / log / heartbeat / finished / failed
#
# Autonomy boundary: the agent edits and runs commands only inside this
# container (hence --yolo: the container IS the sandbox). This harness — not
# the model — pushes a feature branch and opens a PR for a run whose plan a
# human approved. Nothing here can push to the base branch or merge.
# -----------------------------------------------------------------------------
set -euo pipefail

: "${FOREMAN_URL:?}" "${TASK_TOKEN:?}" "${MODEL_API_KEY:?}" "${GH_TOKEN:?}"
export GH_TOKEN
WORK=/workspace/task
LOG="$(mktemp)"

api() { # api <method> <path> [json-body]
  local -a a=(-fsS --retry 5 --retry-all-errors --max-time 30 -X "$1"
    -H @<(printf 'Authorization: Bearer %s\n' "$TASK_TOKEN"))
  [ $# -ge 3 ] && a+=(-H 'Content-Type: application/json' --data-binary "$3")
  curl "${a[@]}" "${FOREMAN_URL%/}$2"
}
event() { # event <type> [message] [extra-json]
  api POST /api/worker/events "$(jq -cn --arg t "$1" --arg m "${2:-}" --argjson x "${3:-{\}}" \
    '{type: $t} + (if $m == "" then {} else {message: $m} end) + $x')" >/dev/null || true
}
fail() {
  event failed "$1" "$(jq -cn --arg l "$(tail -c 4000 "$LOG" 2>/dev/null)" '{log_tail: $l}')"
  exit 1
}
trap 'fail "worker crashed at line $LINENO"' ERR

task="$(api GET /api/worker/task)" || {
  echo "cannot fetch task" >&2
  exit 1
}
get() { jq -r "$1" <<<"$task"; }
repo="$(get .repo_url)" base="$(get .base_branch)" branch="$(get .branch)"
title="$(get .title)" max_turns="$(get '.limits.max_turns // 60')" timeout_s="$(get '.limits.timeout_s // 3600')"
event started "cloning ${repo}"

# Heartbeat so Foreman can tell a slow agent from a dead container.
(while sleep 60; do event heartbeat; done) &
hb=$!
trap 'kill $hb 2>/dev/null || true' EXIT

gh auth setup-git >/dev/null
git clone --quiet --filter=blob:none --branch "$base" "$repo" "$WORK" >>"$LOG" 2>&1 || fail "clone failed"
cd "$WORK"
git checkout --quiet -b "$branch"
git config user.name "devbox-agent"
git config user.email "devbox-agent@users.noreply.github.com"

# A private Hermes home per task, pointed at the run's model.
export HERMES_HOME="$(mktemp -d)"
hermes config set model.provider custom >/dev/null
hermes config set model.base_url "$(get .model.base_url)" >/dev/null
hermes config set model.default "$(get .model.name)" >/dev/null
hermes config set model.api_key "$MODEL_API_KEY" >/dev/null
hermes config set agent.max_turns "$max_turns" >/dev/null
hermes config set tool_loop_guardrails.hard_stop_enabled true >/dev/null
hermes config set terminal.cwd "$WORK" >/dev/null
hermes config set updates.check false >/dev/null

prompt="$(get .prompt)

Acceptance criteria:
$(jq -r '.acceptance[]? | "- " + .' <<<"$task")

Work only in this repository (${WORK}). Read the files you need, not the whole
tree. Make the smallest change that meets the criteria, add or update tests,
and run them. Do not commit, push or open PRs — the harness does that."

event log "agent started (max ${max_turns} turns, ${timeout_s}s)"
set +e
timeout "$timeout_s" hermes chat -Q --yolo --max-turns "$max_turns" -q "$prompt" >>"$LOG" 2>&1
rc=$?
set -e
event log "agent exited ${rc}: $(tail -c 1500 "$LOG")"
[ "$rc" -eq 124 ] && fail "agent timed out after ${timeout_s}s"

git add -A
git diff --cached --quiet && fail "agent made no changes"

# Independent check: Hermes' run-recipe detector bootstraps, builds and tests
# the project. A task may opt out (limits.verify=false) for repos it can't run.
if [ "$(get '.limits.verify // true')" = true ] && ! hermes verify --skip-start >>"$LOG" 2>&1; then
  fail "verification (bootstrap/build/test) failed after the agent's changes"
fi

git commit --quiet -m "feat: ${title}" -m "Foreman run $(get .run_id), task $(get .task_id). Generated by a DevBox agent."
git push --quiet origin "$branch" >>"$LOG" 2>&1 || fail "push failed"
pr="$(gh pr create --base "$base" --head "$branch" --title "$title" \
  --body "$(printf '%s\n\n---\nForeman run `%s` · task `%s` · generated by a DevBox agent. A human merges.' \
    "$(get .prompt | head -c 3000)" "$(get .run_id)" "$(get .task_id)")" 2>>"$LOG")" || fail "PR creation failed"

event finished "PR opened" "$(jq -cn --arg p "$pr" --arg b "$branch" '{pr_url: $p, branch: $b}')"
