#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# DevBox entrypoint.
#
# Runs on every container start, as the non-root dev user. Its job is to make
# volume-backed state usable and then get out of the way. It must be:
#   * idempotent — it runs on every start, including restarts
#   * fast — it is in the path of `podman compose up` and VS Code attach
#   * non-fatal — a failure here must never stop you getting a shell
# -----------------------------------------------------------------------------
set -uo pipefail

# `list_has <needle>` — read a newline-separated list on stdin, succeed if a
# line equals <needle>. Deliberately not `grep -qx`: grep exits on first match,
# the producer takes SIGPIPE, and `pipefail` turns a present value into an
# absent one, intermittently. See bin/devbox-lib.sh for the long version.
list_has() {
  local needle="$1" line
  while IFS= read -r line; do [ "$line" = "$needle" ] && return 0; done
  return 1
}

log() { printf '\033[2m[devbox]\033[0m %s\n' "$*" >&2; }

DEVBOX_ROOT="${DEVBOX_ROOT:-/opt/devbox}"
DEVBOX_CONFIG="${DEVBOX_CONFIG:-$HOME/.config/devbox}"
DEVBOX_STATE="${DEVBOX_AI_STATE:-$HOME/.local/state/devbox}"

# --- volume-backed directories ----------------------------------------------
# Named volumes mount empty and owned by root on first creation. Creating the
# tree here (rather than in the image) is what makes the volumes actually usable
# without a privileged init container.
mkdir -p \
  "$DEVBOX_CONFIG" "$DEVBOX_STATE" \
  "$HOME/.cache" "$HOME/.local/bin" "$HOME/.local/share" \
  "$HOME/.cache/terraform/plugins" \
  "$HOME/.cache/go/mod" "$HOME/.cache/go/build" \
  "$HOME/.cache/npm" "$HOME/.cache/uv" "$HOME/.cache/pip" \
  "$HOME/.cache/helm" \
  "$HOME/go/bin" \
  2>/dev/null || true
chmod 0700 "$DEVBOX_STATE" 2>/dev/null || true

# --- first-run seeding -------------------------------------------------------
# The image ships defaults; the user gets a writable copy in a volume. That is
# what makes the container disposable and your configuration persistent.
seed() { # seed <src-rel> <dst-abs>
  local src="${DEVBOX_ROOT}/$1" dst="$2"
  [ -e "$dst" ] && return 0
  [ -e "$src" ] || return 0
  mkdir -p "$(dirname "$dst")"
  cp -r "$src" "$dst" 2>/dev/null && log "seeded $(basename "$dst")"
}
seed mcp/servers.yaml "${DEVBOX_CONFIG}/mcp/servers.yaml"
seed ai/models "${DEVBOX_CONFIG}/ai/models"
seed ai/policies "${DEVBOX_CONFIG}/ai/policies"

# --- terraform CLI configuration --------------------------------------------
# Written every start so the plugin cache path always matches the mounted volume.
if [ ! -e "$HOME/.terraformrc" ] || [ "${DEVBOX_FORCE_TFRC:-0}" = "1" ]; then
  cat >"$HOME/.terraformrc" <<EOF
# Generated by the DevBox entrypoint. Delete to stop it being managed.
plugin_cache_dir = "${TF_PLUGIN_CACHE_DIR:-$HOME/.cache/terraform/plugins}"
disable_checkpoint = true
EOF
fi

# --- git ---------------------------------------------------------------------
# Bind-mounted repos are owned by the host uid, which git refuses to trust.
# Marking /workspace safe is the standard, minimal fix.
git config --global --get-all safe.directory 2>/dev/null | list_has '/workspace' ||
  git config --global --add safe.directory '/workspace' 2>/dev/null || true
git config --global --get init.defaultBranch >/dev/null 2>&1 ||
  git config --global init.defaultBranch main 2>/dev/null || true

# --- MCP ---------------------------------------------------------------------
# Render client configs from the registry so the AI clients see a policy-filtered
# view from the very first command.
if command -v mcp >/dev/null 2>&1; then
  mcp render --quiet 2>/dev/null || log "mcp render skipped"
fi

# --- credential hygiene ------------------------------------------------------
# Warn (once, cheaply) if a credential directory was mounted writable. Read-only
# is almost always what you want, and the difference is easy to get wrong in a
# compose file.
for d in "$HOME/.ssh" "$HOME/.aws" "$HOME/.azure" "$HOME/.config/gcloud"; do
  [ -d "$d" ] && [ -w "$d" ] && log "note: $d is mounted writable — consider :ro"
done

exec "$@"
