# =============================================================================
# vLLM API key
# =============================================================================
# The value is generated by an EPHEMERAL random_password and written through
# the write-only `secret_data_wo` argument, so it is never stored in Terraform
# state or in a saved plan file (provider v8: with secret_data_wo_version set,
# refresh does not read the payload back either). The state bucket must still
# be private — it holds everything else about this deployment.
#
# Rotate: bump var.api_key_version. A new secret version is created with a new
# random value; VMs read `latest` at every boot.

ephemeral "random_password" "api_key" {
  length  = 48
  special = false
}

resource "google_secret_manager_secret" "api_key" {
  secret_id = "devbox-models-api-key" # DevBox contract — do not rename.

  replication {
    user_managed {
      replicas {
        location = var.region
      }
    }
  }

  labels = { component = "api-key" }
}

resource "google_secret_manager_secret_version" "api_key" {
  secret                 = google_secret_manager_secret.api_key.id
  secret_data_wo         = ephemeral.random_password.api_key.result
  secret_data_wo_version = var.api_key_version
}

resource "google_secret_manager_secret_iam_member" "accessor" {
  for_each = toset(concat([data.google_service_account.runtime.member], var.iap_tunnel_members))

  secret_id = google_secret_manager_secret.api_key.id
  role      = "roles/secretmanager.secretAccessor"
  member    = each.value
}
