"""Persistence interface. Documents are whole pydantic models; writes replace."""

from __future__ import annotations

from typing import Protocol

from foreman.models import Event, Run, RunStatus, Task


class Store(Protocol):
    async def put_run(self, run: Run) -> None: ...
    async def get_run(self, run_id: str) -> Run | None: ...
    async def list_runs(self, limit: int = 20) -> list[Run]: ...
    async def list_runs_by_status(self, status: RunStatus) -> list[Run]: ...
    async def put_task(self, task: Task) -> None: ...
    async def get_task(self, run_id: str, task_id: str) -> Task | None: ...
    async def list_tasks(self, run_id: str) -> list[Task]: ...
    async def append_event(self, event: Event) -> None: ...
    async def list_events(self, run_id: str, limit: int = 50) -> list[Event]: ...
    async def close(self) -> None: ...
